index:
    path: /
    controller: App\Controller\HomeController::index

email:
    path: /email
    controller: App\Controller\HomeController::email

index_translate:
    path: /translate
    controller: App\Controller\TranslationController::translate

login:
    path: /login
    controller: App\Controller\SecurityController::login

login_clients:
    path: /login-clients
    controller: App\Controller\SecurityController::loginClients

logout:
    path: /logout

index_admin:
    path: /admin/
    controller: App\Controller\AdminController::html

admin_booking_validate_user:
    path: /admin/booking/validate-user/
    controller: App\Controller\AdminController::bookingValidateUser
    condition: 'request.isXmlHttpRequest()'
    methods: [POST]

##
# USERS
##

user_list:
    path: /user-list/
    controller: App\Controller\UserController::listUser

status_user:
    path: /status-user/
    controller: App\Controller\UserController::statusUser
    #condition: 'request.isXmlHttpRequest()'

delete_user:
    path: /delete-user/
    controller: App\Controller\UserController::deleteUser
    #condition: 'request.isXmlHttpRequest()'

password_user:
    path: /password-user/
    controller: App\Controller\UserController::passwordUser
    #condition: 'request.isXmlHttpRequest()'

user_new:
    path: /user-new/
    controller: App\Controller\RegistrationController::userNew

user_create:
    path: /user-create/
    controller: App\Controller\RegistrationController::userCreate